### ISSUE TITLE
Architecture review  - update HAL spec

### ISSUE THREAD

**Issue by chaithents** [rdkcentral/rdk-halif-rmf_audio_capture#6]
An architecture review of RMF_AudioCapture HAL recommended some updates to the HAL spec. See ticket https://ccp.sys.comcast.net/browse/RDK-51290 for more background. Following changes were recommended:

1. Audio format does not specify endianness. This needs to be addressed.
2. Revise documentation to specify that implementation is free to limit their audio format support to a subset of what's mentioned in the header file.
3. RMF_AudioCapture_Start() documentation to be updated to indicate that caller expects INVALID_PARAM response when an unsupported format parameter is set. 
4. RMF_AudioCapture_Start() documentation to be made more explicit about what conditions can cause INVALID_PARAM response.
5. HAL spec to be revised to say that caller expects regular callbacks with 'silence' when there is no audio coming out of the mixer.
6. Fifo size: interface spec must include min-max range. Spec must be explicit that 0 means vendor-choice.
7. Threshold: Specify min-max ranges in spec.
8. Status callback: discuss with maintainer and deprecate if not in use. If it's in use, it must be tested. There is limited information as to what some of the members in that struct mean and what causes them to change.

**Comment by hari22yuva** [comment]
merged to develop
